### PR TITLE
Multiple labels created

### LINKED ISSUE #117: Label suggestion
hacktoberfest

### LINKED ISSUE #118: Label suggestion
Add `Hacktoberfest` 🍺

### LINKED ISSUE #119: Label suggestion
Add Hacktoberfest :100:

### LINKED ISSUE #120: Label suggestion
What about has an hacktoberfest label ?

### LINKED ISSUE #121: Label suggestion
hacktoberfest

### LINKED ISSUE #122: Label suggestion
Hacktoberfest label would be good.

### LINKED ISSUE #124: Label suggestion
up-for-grabs

### LINKED ISSUE #126: hacktoberfest

### LINKED ISSUE #127: first-timers-only

### LINKED ISSUE #128: Label suggestion
Optimization

### LINKED ISSUE #129: Label suggestion
Hacktoberfest

### LINKED ISSUE #131: Label suggestion
hacktoberfest

### LINKED ISSUE #133: Label suggestion
Following are some of the annotations used by "spring-projects/spring-boot".
ideal-for-contribution
first-timers-only

### LINKED ISSUE #138: Css
Try to have a Css Label

### PR DESCRIPTION
**Pull request by xanderyzwich**
css closes #138 
first-timers-only closes #127 
ideal-for-contribution closes #133 
optimization closes #128 
up-for-grabs closes #124 
hacktoberfest closes #117, closes #118, closes #119, closes #120, closes #121, closes #131, closes #122, closes #129, closes #126

### CODE REVIEW

**Comment by despo** [comment]
Hi @xanderyzwich. Thank you for your PR.

The `idea-for-contribution` label should be removed as there are only 10 results when using that filter. The rest seem to return sufficient results to make the cut.

screen shot 2018-11-02 at 21 56 15 1

I would be happy to merge the rest but given the purpose of creating issuehub there should be some clear reason as to what each of those labels is for - http://issuehub.io/label-guide

**Comment by xanderyzwich** [comment]
@despo I have reverted the ideal-for-contribution label and updated a couple of label descriptions.  Please let me know if there are any further concerns

**Comment by despo** [comment]
@xanderyzwich thanks!

**Comment by despo** [comment]
@xanderyzwich :shipit:

**Comment by xanderyzwich** [comment]
I'm glad to help @despo

**Pull request merged**
